repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.11.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css]
