name: app_repository
description: A new Flutter package project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  intl: ^0.17.0
  airqo_api:
    path: ../airqo_api

dev_dependencies:
  coverage: ^1.4.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  test: ^1.21.3