name: app
description: AirQo mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# android test
version: 2.0.9+20018

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.1.8
  json_annotation: ^4.5.0
  http: ^0.13.4
  sqflite: ^2.0.2+1
  cached_network_image: ^3.2.1
  geolocator: ^9.0.0
  flutter_local_notifications: ^9.6.1
  url_launcher: ^6.1.4
  path_provider: ^2.0.11
  animations: ^2.0.3
  provider: ^6.0.3
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  uuid: ^3.0.6
  flutter_svg: ^1.1.1
  location: ^4.4.0
  image_picker: ^0.8.5+3
  country_list_pick: ^1.0.1+6
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  in_app_review: ^2.0.4
  sentry_flutter: ^6.6.1
  lottie: ^1.3.0
  share_plus: ^4.0.8
  flutter_secure_storage: ^5.0.2
  geocoding: ^2.0.4
  flutter_dotenv: ^5.0.2
  auto_size_text: ^3.0.0
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_analytics: ^9.1.10
  firebase_storage: ^10.2.18
  scrollable_positioned_list: ^0.3.2
  visibility_detector: ^0.3.3
  package_info_plus: ^1.4.2
  cloud_functions: ^3.2.17
  webview_flutter: ^3.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_in_app_messaging: ^0.6.0+16
  permission_handler: ^9.2.0
  firebase_crashlytics: ^2.8.2
  workmanager: ^0.5.0
  flutter_cache_manager: ^3.3.0
  path: ^1.8.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  app_repository:
    path: packages/app_repository
  

  # https://pub.dev/packages/http_retry
  # https://pub.dev/packages/retry
  
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/icon/splash_image.png
  image_dark: assets/icon/splash_image.png
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon/airqo_logo.png"
  image_path_android: "assets/icon/airqo_logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  dart_code_metrics: ^4.16.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.1.6
  hive_generator: ^1.1.3

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lottie/
    - .env.dev
    - .env.prod

# https://fonts.google.com/specimen/Inter?query=inter

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
