kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ .Values.horizontalPodAutoscaler.name }}
  namespace: {{ .Values.appMode }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.env.deployment_name }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.horizontalPodAutoscaler.resource }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.target }}
          