name: airqo_api
description: A new Flutter package project.
version: 0.0.1
#homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0
  sentry: ^6.6.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  coverage: ^1.4.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.21.3
