replicaCount: 1
image:
  repository: gcr.io/airqo-250220/pr-previews/netmanager-pr-previews
  tag: 5052bff92cb83a2a488e99e137ead21290a5c52e
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 32104
  targetPort: 80
  port: 80
ingress:
  enabled: false
nodeSelector: {}
torelations: {}
resources:
  requests:
    cpu: 5m
    memory: 20Mi
  limits:
    cpu: 50m
    memory: 80Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 90
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
app:
  name: airqo-dev-platform-frontend
  label: dev-platform-ui
  namespace: development
  configmap: env-platform-development
