# values for platform frontend.
env:
  deployment_name: airqo-stage-platform-frontend
  service_name: airqo-stage-platform-ui-svc
  labels: sta-platform-ui
  secret: env-platform-staging

replicaCount: 2

image:
  repository: us.gcr.io/airqo-250220/airqo-stage-platform-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 31104
  targetPort: 80
  port: 80

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: staging