# values for platform frontend.
env:
  deployment_name: airqo-platform-frontend
  service_name: airqo-platform-ui-svc
  labels: airqo-platform
  secret: env-platform-production

replicaCount: 2

image:
  repository: us.gcr.io/airqo-250220/airqo-platform-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 30104
  targetPort: 80
  port: 80

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: production
