# values for platform frontend.
env:
  deployment_name: airqo-platform-frontend
  labels: airqo-platform
  secret: env-platform-production

replicaCount: 2

image:
  repository: gcr.io/airqo-250220/airqo-platform-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 30104
  targetPort: 80
  port: 80
  name: airqo-platform-ui-svc

ingress:
  enabled: false

nodeSelector: {}
torelations: {}

resources:
  requests:
    # Average usage was 0.00001 vCPU and 60Mi over the last 30 days
    cpu: 5m
    memory: 60Mi
  limits:
    cpu: 100m
    memory: 150Mi

horizontalPodAutoscaler:
  name: airqo-platform-frontend-hpa
  minReplicas: 1
  maxReplicas: 4
  resource: memory
  target: 70

## Application level settings
appMode: production
