# Default values for calibrate-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

calibrate:
  deployment_name: airqo-dev-calibrate-app
  labels: dev-calibrate-app
  namespace: development

replicaCount: 1

image:
  repository: gcr.io/airqo-250220/airqo-dev-calibrate-app
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false

service:
  name: airqo-dev-calibrate-app-svc
  type: NodePort
  protocol: TCP
  port: 80
  targetPort: 80
  nodePort: 31106

resources:
  limits:
    cpu: 50m
    memory: 80Mi
  requests:
    cpu: 5m
    memory: 20Mi

autoscaling:
  name: airqo-stage-calibrate-app-hpa
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
