apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibrate-app.fullname" . }}
  labels:
    {{- include "calibrate-app.labels" . | nindent 4 }}
  namespace: {{ .Values.calibrate.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.calibrate.labels }}
