name: run-tests

# on:
#   pull_request:
#     branches:
#       - staging

on: [pull_request]
  
jobs:
  check:
    name: check for changed frontends
    outputs:
      run_next_platform: ${{ steps.check_files.outputs.run_next_platform }} # next platform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified frontends
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          echo "::set-output name=run_next_platform::false"  

          while IFS= read -r file
          do
            if [[ $file == platform/* ]]; then
              echo "::set-output name=run_next_platform::true"
            fi

          done < files.txt

  ### test next-platform changes ###
  test-next-platform:
    name: test-next-platform
    needs: [check]
    # if: needs.check.outputs.run_next_platform == 'true'
    runs-on: ubuntu-latest  
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          cd platform/
          echo "========== Creating app.yaml file =========="  
          echo "NEXT_PUBLIC_ORIGINAL_PLATFORM=${{ secrets.NEW_PLATFORM_STAGE_ORIGINAL_PLATFORM }}" > .env
          echo "INSTRUMENT_CODE=1" >> .env

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./platform/
          build: yarn build
          start: yarn start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: code-coverage

      - name: Deploy code coverage report 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/lcov-report
          working-directory: ./platform/